### ISSUE TITLE
Scroll to top button not appearing on home page.

### ISSUE THREAD

**Issue by GREGG-CHRISTOFFERSON** [GREGG-CHRISTOFFERSON/lp10#6]

**Comment by GREGG-CHRISTOFFERSON** [comment]
@fdickey Do we want the scroll to top button to appear on the home page as well?  Right now it's only on the newsletters.

**Comment by fdickey** [comment]
I think for now it’s good without one. (Unless Ken wishes to greatly expand the home page content).

**Comment by GREGG-CHRISTOFFERSON** [comment]
Perfect.
